model_name: SAGE
loader_type: MiniF
data_name: tolokers

# preprocess params
norm_type: norm01
preprocess: None
n_bins: 32

# model params
d_hidden: 64

# dyple layer
use_dyple: True
dy_raw_bin_width: True
init_bin_width: False
d_feat_emb: 40

# pre mlp
pre_n_layers: 1  # [0,+inf]
pre_use_bn: True
pre_dropout: 0.3

# gnn
gnn_n_layers: 4  # [1,+inf]
gnn_dropout: 0.2
gnn_use_bn: True
gnn_use_res: True
gnn_agg: max_pool

# mha
use_mha: True
mha_n_layers: 1  # [1,+inf]
mha_n_heads: 2  # [1,+inf]
mha_alpha: 0.1

## post mlp
# post_n_layers: 1  # [1,+inf]
# post_use_bn: True
# post_dropout: 0.1

## pre sage
# use_presage: False

# dataloader params
bs: 64
val_bs: 1280 #11500
#fanouts: [100,100]

# optimization params
lr: 0.001
weight_decay: 0.0001
max_epochs: 22222
patience: 31
device: cuda
device_id: 0
seed: 42
nowandb: True

loss_mode: baseline
focal_gamma: 2.0
focal_alpha: [1.0, 3.0]
rare_num_bins: 5
rare_top_k_features: 10
rare_max_weight: 3.0
rare_fraud_boost: 1.5


